;//Map header file for CHM project
;//Automatically generated by Easy CHM.
;//Website : http://www.zipghost.com
;//Email   : webmaster@zipghost.com
;//Date    : 2013/4/5 12:49:52

;//NOTE:
;//All strings after the ";" are commnets, they will be ignored by the CHM Compiler.

#define IDH_1108	1108	; API 帮助 help-doc.html
#define IDH_1106	1106	; 常量字段值 constant-values.html
#define IDH_1131	1131	; 概览 overview-summary.html
#define IDH_1130	1130	; 概览列表 overview-frame.html
#define IDH_1132	1132	; 类分层结构 overview-tree.html
#define IDH_1129	1129	; 生成的文档 (无标题) index.html
#define IDH_1000	1000	; 所有类 allclasses-frame.html
#define IDH_1001	1001	; 所有类 allclasses-noframe.html
#define IDH_1133	1133	; 序列化表格 serialized-form.html
#define IDH_1107	1107	; 已过时的列表 deprecated-list.html
#define IDH_1002	1002	; BuildConfig com\example\my__day\BuildConfig.html
#define IDH_1016	1016	; com.example.my  day com\example\my__day\package-frame.html
#define IDH_1017	1017	; com.example.my  day com\example\my__day\package-summary.html
#define IDH_1018	1018	; com.example.my  day 类分层结构 com\example\my__day\package-tree.html
#define IDH_1014	1014	; Manifest com\example\my__day\Manifest.html
#define IDH_1015	1015	; Manifest.permission com\example\my__day\Manifest.permission.html
#define IDH_1022	1022	; R com\example\my__day\R.html
#define IDH_1020	1020	; R.attr com\example\my__day\R.attr.html
#define IDH_1021	1021	; R.drawable com\example\my__day\R.drawable.html
#define IDH_1023	1023	; R.id com\example\my__day\R.id.html
#define IDH_1024	1024	; R.layout com\example\my__day\R.layout.html
#define IDH_1025	1025	; R.menu com\example\my__day\R.menu.html
#define IDH_1026	1026	; R.string com\example\my__day\R.string.html
#define IDH_1027	1027	; R.style com\example\my__day\R.style.html
#define IDH_1019	1019	; 程序包 com.example.my  day的使用 com\example\my__day\package-use.html
#define IDH_1003	1003	; 类 com.example.my  day.BuildConfig的使用 com\example\my__day\class-use\BuildConfig.html
#define IDH_1005	1005	; 类 com.example.my  day.Manifest.permission的使用 com\example\my__day\class-use\Manifest.permission.html
#define IDH_1004	1004	; 类 com.example.my  day.Manifest的使用 com\example\my__day\class-use\Manifest.html
#define IDH_1006	1006	; 类 com.example.my  day.R.attr的使用 com\example\my__day\class-use\R.attr.html
#define IDH_1007	1007	; 类 com.example.my  day.R.drawable的使用 com\example\my__day\class-use\R.drawable.html
#define IDH_1009	1009	; 类 com.example.my  day.R.id的使用 com\example\my__day\class-use\R.id.html
#define IDH_1010	1010	; 类 com.example.my  day.R.layout的使用 com\example\my__day\class-use\R.layout.html
#define IDH_1011	1011	; 类 com.example.my  day.R.menu的使用 com\example\my__day\class-use\R.menu.html
#define IDH_1012	1012	; 类 com.example.my  day.R.string的使用 com\example\my__day\class-use\R.string.html
#define IDH_1013	1013	; 类 com.example.my  day.R.style的使用 com\example\my__day\class-use\R.style.html
#define IDH_1008	1008	; 类 com.example.my  day.R的使用 com\example\my__day\class-use\R.html
#define IDH_1029	1029	; AlbumEditActivity com\myday\albums\AlbumEditActivity.html
#define IDH_1028	1028	; AlbumEditActivity.CheckableLayout com\myday\albums\AlbumEditActivity.CheckableLayout.html
#define IDH_1030	1030	; AlbumEditActivity.MyMultiChoiceModeListener com\myday\albums\AlbumEditActivity.MyMultiChoiceModeListener.html
#define IDH_1031	1031	; AlbumFragment com\myday\albums\AlbumFragment.html
#define IDH_1047	1047	; com.myday.albums com\myday\albums\package-frame.html
#define IDH_1048	1048	; com.myday.albums com\myday\albums\package-summary.html
#define IDH_1049	1049	; com.myday.albums 类分层结构 com\myday\albums\package-tree.html
#define IDH_1043	1043	; JournalFragment com\myday\albums\JournalFragment.html
#define IDH_1044	1044	; JournalShowActivity com\myday\albums\JournalShowActivity.html
#define IDH_1045	1045	; MainTapActivity com\myday\albums\MainTapActivity.html
#define IDH_1046	1046	; MapFragment com\myday\albums\MapFragment.html
#define IDH_1051	1051	; PicturesGridShowActivity com\myday\albums\PicturesGridShowActivity.html
#define IDH_1052	1052	; SameLocationAlbumActivity com\myday\albums\SameLocationAlbumActivity.html
#define IDH_1053	1053	; SingleImageActivity com\myday\albums\SingleImageActivity.html
#define IDH_1050	1050	; 程序包 com.myday.albums的使用 com\myday\albums\package-use.html
#define IDH_1032	1032	; 类 com.myday.albums.AlbumEditActivity.CheckableLayout的使用 com\myday\albums\class-use\AlbumEditActivity.CheckableLayout.html
#define IDH_1034	1034	; 类 com.myday.albums.AlbumEditActivity.MyMultiChoiceModeListener的使用 com\myday\albums\class-use\AlbumEditActivity.MyMultiChoiceModeListener.html
#define IDH_1033	1033	; 类 com.myday.albums.AlbumEditActivity的使用 com\myday\albums\class-use\AlbumEditActivity.html
#define IDH_1035	1035	; 类 com.myday.albums.AlbumFragment的使用 com\myday\albums\class-use\AlbumFragment.html
#define IDH_1036	1036	; 类 com.myday.albums.JournalFragment的使用 com\myday\albums\class-use\JournalFragment.html
#define IDH_1037	1037	; 类 com.myday.albums.JournalShowActivity的使用 com\myday\albums\class-use\JournalShowActivity.html
#define IDH_1038	1038	; 类 com.myday.albums.MainTapActivity的使用 com\myday\albums\class-use\MainTapActivity.html
#define IDH_1039	1039	; 类 com.myday.albums.MapFragment的使用 com\myday\albums\class-use\MapFragment.html
#define IDH_1040	1040	; 类 com.myday.albums.PicturesGridShowActivity的使用 com\myday\albums\class-use\PicturesGridShowActivity.html
#define IDH_1041	1041	; 类 com.myday.albums.SameLocationAlbumActivity的使用 com\myday\albums\class-use\SameLocationAlbumActivity.html
#define IDH_1042	1042	; 类 com.myday.albums.SingleImageActivity的使用 com\myday\albums\class-use\SingleImageActivity.html
#define IDH_1058	1058	; com.myday.database com\myday\database\package-frame.html
#define IDH_1059	1059	; com.myday.database com\myday\database\package-summary.html
#define IDH_1060	1060	; com.myday.database 类分层结构 com\myday\database\package-tree.html
#define IDH_1056	1056	; MyDayDatabase com\myday\database\MyDayDatabase.html
#define IDH_1057	1057	; MyDayDatabase.LocationSet com\myday\database\MyDayDatabase.LocationSet.html
#define IDH_1061	1061	; 程序包 com.myday.database的使用 com\myday\database\package-use.html
#define IDH_1055	1055	; 类 com.myday.database.MyDayDatabase.LocationSet的使用 com\myday\database\class-use\MyDayDatabase.LocationSet.html
#define IDH_1054	1054	; 类 com.myday.database.MyDayDatabase的使用 com\myday\database\class-use\MyDayDatabase.html
#define IDH_1064	1064	; com.myday.file com\myday\file\package-frame.html
#define IDH_1065	1065	; com.myday.file com\myday\file\package-summary.html
#define IDH_1066	1066	; com.myday.file 类分层结构 com\myday\file\package-tree.html
#define IDH_1063	1063	; FileHandle com\myday\file\FileHandle.html
#define IDH_1067	1067	; 程序包 com.myday.file的使用 com\myday\file\package-use.html
#define IDH_1062	1062	; 类 com.myday.file.FileHandle的使用 com\myday\file\class-use\FileHandle.html
#define IDH_1086	1086	; com.myday.map com\myday\map\package-frame.html
#define IDH_1087	1087	; com.myday.map com\myday\map\package-summary.html
#define IDH_1088	1088	; com.myday.map 类分层结构 com\myday\map\package-tree.html
#define IDH_1077	1077	; DemoApplication com\myday\map\DemoApplication.html
#define IDH_1078	1078	; GetLocation com\myday\map\GetLocation.html
#define IDH_1079	1079	; ItemizedOverlayDemo com\myday\map\ItemizedOverlayDemo.html
#define IDH_1080	1080	; Location com\myday\map\Location.html
#define IDH_1081	1081	; Location.MyLocationListenner com\myday\map\Location.MyLocationListenner.html
#define IDH_1082	1082	; Location.NotifyLister com\myday\map\Location.NotifyLister.html
#define IDH_1083	1083	; Map Activity com\myday\map\Map_Activity.html
#define IDH_1084	1084	; Map Activity.OverItem com\myday\map\Map_Activity.OverItem.html
#define IDH_1085	1085	; Over Item com\myday\map\Over_Item.html
#define IDH_1089	1089	; 程序包 com.myday.map的使用 com\myday\map\package-use.html
#define IDH_1068	1068	; 类 com.myday.map.DemoApplication的使用 com\myday\map\class-use\DemoApplication.html
#define IDH_1069	1069	; 类 com.myday.map.GetLocation的使用 com\myday\map\class-use\GetLocation.html
#define IDH_1070	1070	; 类 com.myday.map.ItemizedOverlayDemo的使用 com\myday\map\class-use\ItemizedOverlayDemo.html
#define IDH_1072	1072	; 类 com.myday.map.Location.MyLocationListenner的使用 com\myday\map\class-use\Location.MyLocationListenner.html
#define IDH_1073	1073	; 类 com.myday.map.Location.NotifyLister的使用 com\myday\map\class-use\Location.NotifyLister.html
#define IDH_1071	1071	; 类 com.myday.map.Location的使用 com\myday\map\class-use\Location.html
#define IDH_1075	1075	; 类 com.myday.map.Map Activity.OverItem的使用 com\myday\map\class-use\Map_Activity.OverItem.html
#define IDH_1074	1074	; 类 com.myday.map.Map Activity的使用 com\myday\map\class-use\Map_Activity.html
#define IDH_1076	1076	; 类 com.myday.map.Over Item的使用 com\myday\map\class-use\Over_Item.html
#define IDH_1090	1090	; Album com\myday\pictures\Album.html
#define IDH_1099	1099	; com.myday.pictures com\myday\pictures\package-frame.html
#define IDH_1100	1100	; com.myday.pictures com\myday\pictures\package-summary.html
#define IDH_1101	1101	; com.myday.pictures 类分层结构 com\myday\pictures\package-tree.html
#define IDH_1097	1097	; Journal com\myday\pictures\Journal.html
#define IDH_1098	1098	; JournalAlbum com\myday\pictures\JournalAlbum.html
#define IDH_1103	1103	; Photo com\myday\pictures\Photo.html
#define IDH_1104	1104	; PhotoAlbum com\myday\pictures\PhotoAlbum.html
#define IDH_1105	1105	; Picture com\myday\pictures\Picture.html
#define IDH_1102	1102	; 程序包 com.myday.pictures的使用 com\myday\pictures\package-use.html
#define IDH_1091	1091	; 类 com.myday.pictures.Album的使用 com\myday\pictures\class-use\Album.html
#define IDH_1093	1093	; 类 com.myday.pictures.JournalAlbum的使用 com\myday\pictures\class-use\JournalAlbum.html
#define IDH_1092	1092	; 类 com.myday.pictures.Journal的使用 com\myday\pictures\class-use\Journal.html
#define IDH_1095	1095	; 类 com.myday.pictures.PhotoAlbum的使用 com\myday\pictures\class-use\PhotoAlbum.html
#define IDH_1094	1094	; 类 com.myday.pictures.Photo的使用 com\myday\pictures\class-use\Photo.html
#define IDH_1096	1096	; 类 com.myday.pictures.Picture的使用 com\myday\pictures\class-use\Picture.html
#define IDH_1109	1109	; A - 索引 index-files\index-1.html
#define IDH_1120	1120	; B - 索引 index-files\index-2.html
#define IDH_1122	1122	; C - 索引 index-files\index-3.html
#define IDH_1123	1123	; D - 索引 index-files\index-4.html
#define IDH_1124	1124	; E - 索引 index-files\index-5.html
#define IDH_1125	1125	; F - 索引 index-files\index-6.html
#define IDH_1126	1126	; G - 索引 index-files\index-7.html
#define IDH_1127	1127	; H - 索引 index-files\index-8.html
#define IDH_1128	1128	; I - 索引 index-files\index-9.html
#define IDH_1110	1110	; J - 索引 index-files\index-10.html
#define IDH_1111	1111	; L - 索引 index-files\index-11.html
#define IDH_1112	1112	; M - 索引 index-files\index-12.html
#define IDH_1113	1113	; O - 索引 index-files\index-13.html
#define IDH_1114	1114	; P - 索引 index-files\index-14.html
#define IDH_1115	1115	; R - 索引 index-files\index-15.html
#define IDH_1116	1116	; S - 索引 index-files\index-16.html
#define IDH_1117	1117	; T - 索引 index-files\index-17.html
#define IDH_1118	1118	; U - 索引 index-files\index-18.html
#define IDH_1119	1119	; V - 索引 index-files\index-19.html
#define IDH_1121	1121	; W - 索引 index-files\index-20.html
